[package]
name = "hello"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://github.com/paritytech/polkaports"
repository = "https://github.com/paritytech/polkaports"
license = "Apache-2.0"
version = "0.1.0"
publish = false

[workspace]
